// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"task-manager/auth"
	"task-manager/internal/repository/postgres"
	"task-manager/internal/rest"
	"task-manager/internal/rest/middleware"
	"task-manager/pkg/jwtutil"
	"task-manager/pkg/keycloak"
	"task-manager/project"
	"task-manager/task"
	"task-manager/user"
)

// Injectors from wire.go:

func InitializeServer() (*rest.Server, error) {
	publicKey, err := jwtutil.FetchRSAPublicKeyFromJWKS()
	if err != nil {
		return nil, err
	}
	handlerFunc := middleware.JWTAuthMiddleware(publicKey)
	client := keycloak.NewClient()
	service := auth.NewService(client)
	db, err := postgres.NewDB()
	if err != nil {
		return nil, err
	}
	taskRepository := postgres.NewTaskRepository(db)
	commentRepository := postgres.NewCommentRepository(db)
	taskService := task.NewService(taskRepository, commentRepository)
	userService := user.NewService(taskRepository)
	projectService := project.NewService(taskRepository)
	server := rest.NewServer(handlerFunc, service, taskService, userService, projectService)
	return server, nil
}
